baseurl = "http://www.hedgehogaviation.com"
title = "Hedgehog Aviation"

theme = "hugo-coder"

[params]
    author = "Hedgehog Aviation Services"
    description = "Hedgehog Aviation place holder"
    keywords = "Flying, ecommerce, blog"
    info = "Coming soon"
    #avatarurl = "images/avatar.jpg"
    footercontent = "Nothing here yet."

[taxonomies]
    series = "series"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
